import 'package:flutter/widgets.dart';
class IconFont {
    IconFont._();
    static const font_name = 'IconFont'; 
      static const IconData add = const IconData(0xe1, fontFamily: font_name);
  static const IconData chuangjianzhibo = const IconData(0xe606, fontFamily: font_name);
  static const IconData close = const IconData(0xe6, fontFamily: font_name);
  static const IconData delete = const IconData(0xe13, fontFamily: font_name);
  static const IconData edit = const IconData(0xe14, fontFamily: font_name);
  static const IconData edit_live = const IconData(0xe703, fontFamily: font_name);
  static const IconData ellipsis = const IconData(0xe21, fontFamily: font_name);
  static const IconData fail = const IconData(0xe616, fontFamily: font_name);
  static const IconData fund_management = const IconData(0xe104, fontFamily: font_name);
  static const IconData go_back = const IconData(0xe5, fontFamily: font_name);
  static const IconData go_forward = const IconData(0xe4, fontFamily: font_name);
  static const IconData goto = const IconData(0xe10, fontFamily: font_name);
  static const IconData jiudaye = const IconData(0xe107, fontFamily: font_name);
  static const IconData live = const IconData(0xe101, fontFamily: font_name);
  static const IconData live_thumb = const IconData(0xe702, fontFamily: font_name);
  static const IconData live_visitor = const IconData(0xe701, fontFamily: font_name);
  static const IconData mine_active = const IconData(0xe602, fontFamily: font_name);
  static const IconData mine_inactive = const IconData(0xe603, fontFamily: font_name);
  static const IconData minus = const IconData(0xe2, fontFamily: font_name);
  static const IconData next = const IconData(0xe18, fontFamily: font_name);
  static const IconData off_shelves = const IconData(0xe12, fontFamily: font_name);
  static const IconData order = const IconData(0xe15, fontFamily: font_name);
  static const IconData order_management = const IconData(0xe103, fontFamily: font_name);
  static const IconData play = const IconData(0xe17, fontFamily: font_name);
  static const IconData product_management = const IconData(0xe102, fontFamily: font_name);
  static const IconData release_active = const IconData(0xe601, fontFamily: font_name);
  static const IconData release_inactive = const IconData(0xe600, fontFamily: font_name);
  static const IconData search = const IconData(0xe9, fontFamily: font_name);
  static const IconData setting = const IconData(0xe108, fontFamily: font_name);
  static const IconData share = const IconData(0xe8, fontFamily: font_name);
  static const IconData share_link = const IconData(0xe16, fontFamily: font_name);
  static const IconData shelves = const IconData(0xe11, fontFamily: font_name);
  static const IconData success = const IconData(0xe604, fontFamily: font_name);
  static const IconData tianjiashangpin = const IconData(0xe60a, fontFamily: font_name);
  static const IconData visit_live = const IconData(0xe704, fontFamily: font_name);
  static const IconData wechat = const IconData(0xe105, fontFamily: font_name); 
}